codecov:
  require_ci_to_pass: true

coverage:
  status:
    project:
      default:
        target: auto
        threshold: 5%
    patch:
      default:
        target: 80%

flag_management:
  default_rules:
    carryforward: true
  individual_flags:
    - name: backend
      paths:
        - backend/src/
        - backend/generator/
        - backend/kafka/
    - name: frontend
      paths:
        - frontend/src/
